### ISSUE TITLE
Unable to clone repository causing entire installation to fail

### ISSUE THREAD

**Issue by DaytonaBlep** [invoke-ai/invoke-training#150]
I tried many alternative methods of cloning, but everything ended like this:
`C:\Users\Daytona>gh repo clone invoke-ai/invoke-training F:\AIStuff\Training
Cloning into 'F:\AIStuff\Training'...
remote: Enumerating objects: 9073, done.
remote: Counting objects: 100% (1681/1681), done.
remote: Compressing objects: 100% (566/566), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 6399 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
failed to run git: exit status 128`
I'm not sure I know what to do in this case.

**Comment by DaytonaBlep** [comment]
I figured out the cloning, I had other problems during the installation, I don't understand how to isolate the environments, the modules still start to conflict with the Invokeai environment

**Comment by ebr** [comment]
You should use a tool like `pyenv` to create isolated virtual environments.

I'm going to close the issue since the original problem was resolved (this StackOverflow thread may help folks finding this issue in the future: https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed#22317479).

If you still need any assistance with virtual environments, etc, please feel free to ask in Discord - the community will happy to help.
